### ISSUE TITLE
Make Connection class singleton

### ISSUE THREAD

**Issue by roback** [twingly/twingly-amqp#10]
There should only be one connection instance.

If it is a singleton, `Ping.new` and `Subscription.new` can just call `Connection.instance` instead of having the client pass a connection object to their constructors. (see [chapman](https://github.com/twingly/chapman/blob/master/chapman.rb#L40-L50))

**Comment by roback** [comment]
If we do this we have to set the `RABBITMQ_\d+_HOST` variables in all projects. (Chapman currently uses srv records from https://github.com/twingly/twingly-configuration)

**Comment by roback** [comment]
> Either we make Connection a subclass of Bunny

That isn't possible since `Bunny` is a module, on which they have implemented `self.new`: https://github.com/ruby-amqp/bunny/blob/master/lib/bunny.rb#L61

**Comment by roback** [comment]
It's hard to test the singleton class since its only initialized once. To test it with different ENVs you have to run `described_class.send(:new)` to  be able to create a new instance. Don't know if singleton was such a good idea as it seemed like at first :(

@jage

**Comment by jage** [comment]
Could the singleton be a wrapper around an ordinary class (Twingly::AMQP::Session)? All tests will be in Session, and the singleton-class will only be responsible for being a singleton. We can do a video chat after lunch if you'd like.

**Comment by roback** [comment]
Aha, so Connection will have one "setup" method (for when you want to use custom options) and one ".instance" method which returns the same instance all the time. I think that would work, thanks :)
