### ISSUE TITLE
Optional ping options

### ISSUE THREAD

**Issue by jage** [twingly/twingly-amqp#2]
Could we make the following options optional with the following defaults
- priority: 3
- queue_name: provider-ping

**Comment by roback** [comment]
> * queue_name: provider-ping

Not sure about that part as we nowadays usually call the queues `<environment>.<appname>.<queuename>` (we don't use that prefix for the ping queues at the moment, but we have an issue about renaming them, see twingly/norrstrom#14).

I will just close this issue as I don't think it's worth adding a default for just priority. I like that we have it explicitly defined in each app that uses twingly-amqp. Anyone who disagrees can just open it again :)
