### ISSUE TITLE
Timeout threshold too low, increase or refactor?

### ISSUE THREAD

**Issue by walro** [twingly/twingly-amqp#44]
To ensure our test suite does not run forever we have wrapped all subscription tests [with a timeout](https://github.com/twingly/twingly-amqp/blob/0ac43978de16043e67b3984741d8e76462f97ae1/spec/integration/twingly/amqp/subscription_spec.rb#L5-L11). The timeout was reached [at least once](https://github.com/twingly/twingly-amqp/pull/43#issuecomment-220930078) without any test case being "broken".

Maybe we need a longer timeout or smarter logics (to avoid timeouts altogether).

**Comment by dentarg** [comment]
> smarter logics (to avoid timeouts altogether)

I want this.

**Comment by walro** [comment]
Maybe this is the idiomatic way to do it and we should increase the timeout? WDYT @dentarg my fellow Ruby Tapas 154'er? :)

**Comment by walro** [comment]
Possibly we want to decrease the scope though, make it more like the episode – explicitly calling where needed instead of wrapping each test with it

**Comment by dentarg** [comment]
> Possibly we want to decrease the scope though, make it more like the episode – explicitly calling where needed instead of wrapping each test with it

Sounds good

**Comment by dentarg** [comment]
> Maybe this is the idiomatic way to do it and we should increase the timeout? WDYT @dentarg my fellow Ruby Tapas 154'er? :)

Yeah, maybe the timeouts can stay... I think I was more thinking of getting rid of unessarcy `sleep`s

**Comment by walro** [comment]
I think I have found a way to get rid of the sleeps, PR coming later on :)

**Comment by walro** [comment]
> I think I have found a way to get rid of the sleeps, PR coming later on :)

Sneek peek in c2f69908d55c0dfdcd1b655959b40d3e3bf7ecbe
