### ISSUE TITLE
Possible to stop/cancel the subscription from caller

### ISSUE THREAD

**Issue by walro** [twingly/twingly-amqp#45]
Related to #29.

To get some cleaner tests it might be a good idea to be able to `cancel` from the outside (right now it's just possible via interrupts). In that way we could cleanly exit.

**Comment by dentarg** [comment]
> right now it's just possible via interrupts

Since https://github.com/twingly/twingly-amqp/commit/22c799377a17274475c82e7e49fa7cabb62843db#diff-dad5e21a79b90b462ebf9695f101a6dbL37 I don't think that is true anymore

**Comment by roback** [comment]
> Since 22c7993#diff-dad5e21a79b90b462ebf9695f101a6dbL37 I don't think that is true anymore

You´re right, and the `cancel!` method was introduced in https://github.com/twingly/twingly-amqp/commit/b31b4d0d5d0103228d85a4dabe90c71069c7bbd2. Since then it's possible to stop the subscription, so this can be closed.

**Comment by dentarg** [comment]
No, `cancel!` (and `cancel?`) was added in https://github.com/twingly/twingly-amqp/commit/977d08ba2c66fa810844845614cca681a7696c0e (21 Oct 2015)

So I wonder if this issues was about something else as it was created in 2016?

But yes, it looks like it can be closed, unless I'm missing something, didn't think of that yesterday. :)
