### ISSUE TITLE
Remove workaround for "frozen array" error in bunny

### ISSUE THREAD

**Issue by roback** [twingly/twingly-amqp#57]
The following PR adds a workaround for a `Can't modify frozen array` in bunny: https://github.com/twingly/twingly-amqp/pull/55

The issue has been reported and solved in bunny (https://github.com/ruby-amqp/bunny/issues/446), but it has not yet been released. When it is released we can remove the workaround in #55. We also have to lock bunny to a newer version in the gemspec file.

**Comment by walro** [comment]
Newer Bunny version has been released now.

**Comment by walro** [comment]
remember to change the gemspec (we require at least the version that includes the fix) when removing the workaround
