### ISSUE TITLE
Remove signal trap code

### ISSUE THREAD

**Issue by jage** [twingly/twingly-amqp#63]
It's probably not the best idea to setup signal traps in a gem since the apps using it might have different ideas on how it should handle signals.

https://github.com/twingly/twingly-amqp/blob/b1bba55dafe5637fac9c72b72bb8d26b4aae571c/lib/twingly/amqp/subscription.rb#L116-L126

**Comment by jage** [comment]
A first step could be to release a version where we can disable the traps, but keep them as defaults to avoid breaking anything that's relying on them.

**Comment by jage** [comment]
Hmm, is this code even called? I can't find any calls to `setup_traps` in the gem, and it's a private method. I think the call was removed in 22c799377a17274475c82e7e49fa7cabb62843db

**Comment by roback** [comment]
> Hmm, is this code even called? I can't find any calls to setup_traps in the gem, and it's a private method. I think the call was removed in 22c7993

Hmm... looks like it. I don't think it was removed intentionally though :)
